name: Tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - .gitignore
      - docker-compose.yml
      - .github/workflows/docker-hub-description.yml
      - .github/workflows/update-versions.yml
      - .github/workflows/update-versions.py
      - .github/workflows/requirements.txt
      - .github/workflows/build-publish.yml
      - LICENSE
      - '**.md'
      
jobs:
  tests:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Load .env file and set as environment variables
        run: cat .env >> $GITHUB_ENV
        
      - name: Build
        uses: docker/build-push-action@v5
        with:  
          tags: pleandre/dev-container:tests-${{ github.sha }}
          build-args: |
            DEBIAN_CODENAME=${{ env.DEBIAN_CODENAME }}
            DEV_CONTAINER_USER=${{ env.DEV_CONTAINER_USER }}
          file: Dockerfile
          context: .
          push: false
          load: true # Needed to load the image into the Docker environment
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: |
          docker run --name tests-container -v $GITHUB_WORKSPACE/tests:/tests pleandre/dev-container:tests-${{ github.sha }} /tests/run-tests.sh
          tests_exit_code=$?
          docker rm tests-container
          if [ $tests_exit_code -ne 0 ]; then
            echo "Tests failed with exit code $tests_exit_code"
            exit 1
          fi
          
      - name: Automatically merge Dependabot PRs
        uses: pascalgn/automerge-action@v0.16.2
        if: github.actor == 'dependabot[bot]' || github.actor == 'github-actions[bot]'
        with:
          mergeMethod: squash
          token: ${{ secrets.GITHUB_TOKEN }}